site_name: AI Moderation Project Documentation
site_description: Documentation for the AI Moderation Project
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Features:
    - Core Features: features/core-features.md
    - Architecture: features/architecture.md
  - API Reference:
    - API Overview: api/overview.md
    - Endpoints: api/endpoints.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - footnotes
  - toc:
      permalink: true 